import { render, screen } from '@testing-library/react'
import PersonalOrganizerPage from '@/app/personal/page'

describe('PersonalOrganizerPage', () => {
  it('renders owner daily personal organizer mode with safety boundaries', () => {
    render(<PersonalOrganizerPage />)

    expect(screen.getByText('Humanity Guide OS - Personal Organizer Mode')).toBeInTheDocument()
    expect(screen.getByText('Owner daily surface')).toBeInTheDocument()
    expect(screen.getByText('First Use Workflow')).toBeInTheDocument()
    expect(screen.getByText('Step 1')).toBeInTheDocument()
    expect(screen.getAllByText('Choose what to organize').length).toBeGreaterThan(0)
    expect(screen.getByText('Step 2')).toBeInTheDocument()
    expect(screen.getByText('Preview chaos')).toBeInTheDocument()
    expect(screen.getByText('Step 3')).toBeInTheDocument()
    expect(screen.getByText('Review proposals')).toBeInTheDocument()
    expect(screen.getByText('Step 4')).toBeInTheDocument()
    expect(screen.getByText('Generate manual checklist')).toBeInTheDocument()
    expect(screen.getByText('Step 5')).toBeInTheDocument()
    expect(screen.getByText('Owner executes manually outside the app')).toBeInTheDocument()
    expect(screen.getByText('Downloads')).toBeInTheDocument()
    expect(screen.getByText('Desktop')).toBeInTheDocument()
    expect(screen.getByText('Pictures')).toBeInTheDocument()
    expect(screen.getAllByText('Screenshots').length).toBeGreaterThan(0)
    expect(screen.getByText('Emails')).toBeInTheDocument()
    expect(screen.getByText('Project files')).toBeInTheDocument()
    expect(screen.getByText('One place to reduce daily chaos')).toBeInTheDocument()
    expect(screen.getByText('`/personal` is the owner-facing mode. `/lab` remains the technical governance and blueprint surface.')).toBeInTheDocument()
    expect(screen.getByText('Documents need review')).toBeInTheDocument()
    expect(screen.getByText('Photos need lightweight grouping')).toBeInTheDocument()
    expect(screen.getByText('Inbox needs owner decisions')).toBeInTheDocument()
    expect(screen.getByText('Daily priorities can be reduced')).toBeInTheDocument()
    expect(screen.getByText('Personal Organization Plan')).toBeInTheDocument()
    expect(screen.getByText('What to sort first, why it matters, and how to stay safe')).toBeInTheDocument()
    expect(screen.getAllByText('Sort first').length).toBeGreaterThan(0)
    expect(screen.getAllByText('Estimated time').length).toBeGreaterThan(0)
    expect(screen.getAllByText('Expected impact').length).toBeGreaterThan(0)
    expect(screen.getByText("Today's Focus")).toBeInTheDocument()
    expect(screen.getByText('What I do today')).toBeInTheDocument()
    expect(screen.getByText('What I do not touch')).toBeInTheDocument()
    expect(screen.getByText('What I review manually')).toBeInTheDocument()
    expect(screen.getByText('Begin with 20 minutes on Downloads, then stop and review the checklist.')).toBeInTheDocument()
    expect(screen.getByText('Personal usefulness without unsafe automation')).toBeInTheDocument()
    expect(screen.getByText('readOnlyFirst: true')).toBeInTheDocument()
    expect(screen.getByText('proposalFirst: true')).toBeInTheDocument()
    expect(screen.getByText('approvalRequired: true')).toBeInTheDocument()
    expect(screen.getAllByText('actionExecuted: false').length).toBeGreaterThan(0)
    expect(screen.getByText('filesystemWriteAccess: false')).toBeInTheDocument()
    expect(screen.getByText('filesystemDeleteAccess: false')).toBeInTheDocument()
    expect(screen.getByText('filesystemMoveAccess: false')).toBeInTheDocument()
    expect(screen.getByText('emailSendAccess: false')).toBeInTheDocument()
    expect(screen.getByText('No files moved')).toBeInTheDocument()
    expect(screen.getByText('No files deleted')).toBeInTheDocument()
    expect(screen.getByText('No email sent')).toBeInTheDocument()
    expect(screen.getByText('Manual execution only')).toBeInTheDocument()
    expect(screen.getByText('Owner approval required')).toBeInTheDocument()
    expect(screen.getByText('backgroundAgents: false')).toBeInTheDocument()
  })
})
